import { z } from "zod";

/**
 * Validation + shaping for share tokens and the `get_share` RPC response
 * (Milestone 5).
 *
 * `get_share` is SECURITY DEFINER and itself enforces the spoiler gate — see
 * `supabase/migrations/20260909003915_sharing.sql`. This module only
 * re-validates *shape*, same boundary discipline as `results-schema.ts` /
 * `schema.ts`.
 */

// Postgres `uuid` text form — duplicated per read-boundary module, matching
// the rest of `lib/game/*`.
const uuid = z
  .string()
  .regex(
    /^[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$/,
    "expected a uuid",
  );

/**
 * A share token as actually generated by `create_share`
 * (`encode(gen_random_bytes(16), 'hex')` — always 32 lowercase hex chars),
 * loosened slightly to the database's own `shares_token_len` check
 * constraint (16-64 chars) so a future token format doesn't need a schema
 * change here too. Anything outside this shape is rejected before it ever
 * reaches the database — not a security boundary (the RPC parameter is
 * bound, not interpolated), just an early, cheap "this can't possibly be a
 * real token" exit that renders the same generic invalid-link state as a
 * real not-found token (docs/SECURITY.md sec 11).
 */
export const shareTokenSchema = z
  .string()
  .regex(/^[0-9a-f]{16,64}$/, "expected a share token");

const senderSchema = z
  .object({
    username: z.string().nullable(),
    display_name: z.string().nullable(),
  })
  .nullable();

const teaserTierlistSchema = z.object({
  slug: z.string().min(1),
  title: z.string().min(1),
  prompt: z.string().nullable(),
});

const shareRankingItemSchema = z.object({
  item_id: uuid,
  label: z.string().min(1),
  image_url: z.string().nullable(),
  tier: z.string().min(1).max(8),
  position: z.number().int().nonnegative(),
});

/** `get_share`'s full JSON shape — a token that exists is `found: true` with
 *  a teaser always, plus the ranking only once `locked` is `false`. A
 *  missing/revoked token is `{found: false}` and nothing else. */
export const getShareResponseSchema = z.union([
  z.object({
    found: z.literal(true),
    sender: senderSchema,
    tierlist: teaserTierlistSchema,
    locked: z.boolean(),
    ranking: z.array(shareRankingItemSchema).nullable(),
  }),
  z.object({ found: z.literal(false) }),
]);

export type ShareRankingItem = {
  itemId: string;
  label: string;
  imageUrl: string | null;
  tier: string;
  position: number;
};

/**
 * A found share, reshaped into camelCase. Only ever constructed for
 * `found: true` — `getShare()` (`lib/game/get-share.ts`) folds `found: false`
 * into `null`, so this type never needs to carry that branch.
 */
export type ShareTeaser = {
  senderUsername: string | null;
  senderDisplayName: string | null;
  tierlistSlug: string;
  tierlistTitle: string;
  tierlistPrompt: string | null;
  locked: boolean;
  /** Populated only when `locked` is `false`. */
  ranking: ShareRankingItem[] | null;
};

/**
 * Validate a raw `get_share` payload and shape a `found: true` response into
 * `ShareTeaser`. Returns `null` for `found: false`. Throws `ZodError` if the
 * payload matches neither shape — that should only ever happen on a
 * schema/RPC drift.
 */
export function mapShare(raw: unknown): ShareTeaser | null {
  const parsed = getShareResponseSchema.parse(raw);
  if (!parsed.found) return null;

  return {
    senderUsername: parsed.sender?.username ?? null,
    senderDisplayName: parsed.sender?.display_name ?? null,
    tierlistSlug: parsed.tierlist.slug,
    tierlistTitle: parsed.tierlist.title,
    tierlistPrompt: parsed.tierlist.prompt,
    locked: parsed.locked,
    ranking: parsed.ranking
      ? parsed.ranking.map((r) => ({
          itemId: r.item_id,
          label: r.label,
          imageUrl: r.image_url,
          tier: r.tier,
          position: r.position,
        }))
      : null,
  };
}
